extends:
  - plugin:prettier/recommended
  - plugin:react/recommended

parser: babel-eslint

env:
  browser: true
  node: true

plugins:
  - react-hooks
  - babel

rules:
  prettier/prettier: 2
  no-console: 0
