name: Testing build and health code

on: [pull-request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
      steps:
            strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        env:
          CI: true
          DB: postgres
          HOST: localhost
          DB_PASSWORD: postgres
          PD_PORT: 5432
          DB_USER: postgres
          PORT: 3000
          SECRET: secret
  

